Repository viniciusfersil123/dub-siren, pull requests merged in 2025-07, with the labels that each got.

#38 #24 - remapeia volume de linear para exponencial
  dub.cpp
Labels: Volume

#43 #31 - Ajustar frequência mínima e máxima do filtro
  dub.h
Labels: Sweep

#39 #29 Mudar mapeamento do Rate para exponencial
  dub.cpp
Labels: Rate

#62 #55 - Arrumar lógica do sweep to tune
  dub.cpp
  dub.h
Labels: Sweep

#63 #30 - Forma do LFO fica travada no último botão apertado
  dub.cpp
  dub.h
Labels: Triggers
