Repository viniciusfersil123/dub-siren, pull requests merged in 2025-08, with the labels that each got.

#65 #28 - Diminuir a frequência mínima inferior do Rate
  dub.h
Labels: Rate

#67 #56 - Refatorar cálculo do depth_exp usando a função pow10f ao invés de powf
  dub.cpp
Labels: Depth

#71 #50 Desacoplar a curva da cutoff do VCF com trigger pressionado da curva da intensidade do sweep com trigger solto
  dub.cpp
  dub.h
Labels: Sweep

#74 #20 Adicionar fclamp na leitura dos knobs da função UpdateAll()
  dub.cpp
Labels: refactor
